# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ravi Balami
title: Data Analyst
#website: www.ravibalami.github.io
email: ravibalami1@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ravibalami
github_username:  ravibalami
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ravibalami
linkedin_username: ravibalami
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: ravibalami
  icon: fas fa-globe
  url: https://ravibalami.github.io/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ravi.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a dedicated Data Analyst with several years of experience in analyzing and optimizing data from diverse sources, including Google Data Studio, SQL, and Excel. Skilled at identifying inefficiencies and solving complex problems, I am passionate about transforming raw data into clear, actionable insights. I excel in collaborating with colleagues and clients to ensure project goals are met and delivering data-driven solutions that drive meaningful business success.

  I am most skilled in: <mark>Data Analysis</mark> , <mark>SQL & Python</mark> and <mark>Data Visualization</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ATM System with Facial Recognition
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This system is designed to provide an additional layer of security and convenience for users, allowing them to access their accounts and conduct transactions without the need for cards or passwords.
        description: | # this will include new lines to allow paragraphs
          In the ATM Facial Recognition System project, I utilized <mark>Python</mark> and the <mark>face_recognition library</mark> to implement facial recognition for secure, contactless user authentication. The system was built using <mark>OpenCV</mark> for image processing and deployed with <mark>Docker</mark> on <mark>AWS</mark> for scalability and high availability. Additionally, <mark>SSL/TLS protocols</mark> were implemented to secure user transactions, ensuring data privacy and integrity.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sticks'n'Sushi
        link: https://www.sticksnsushi.com/gb/en/
        # link_text: boringcompany.com
        sub_title: BOH Manager
        caption: March 2022 - Present
        quote: >
          Skills in leadership, data organization, and problem-solving from my BOH Manager role directly support my ability to analyze data, optimize processes, and drive data-driven insights.
        description: | # this will include new lines to allow paragraphs
            As a BOH Manager, I developed a wide range of transferable skills that are highly applicable to my new role as a Data Analyst. My experience in leadership and team management will help me collaborate effectively across teams, while my ability to oversee operations, manage time efficiently, and ensure smooth workflows directly translates to managing data projects and optimizing processes. My background in data organization, such as managing inventory and stock levels, will assist in organizing and analyzing datasets, ensuring data integrity. Additionally, my experience with problem-solving and process improvement in high-pressure kitchen environments will be valuable for troubleshooting and optimizing data pipelines. I also bring expertise in financial management, including budgeting and cost analysis, which aligns with analyzing financial data and making data-driven decisions. My attention to detail, honed through quality control in food preparation, will ensure accuracy in data analysis, while my understanding of risk management and compliance translates well into managing data privacy and adhering to regulations like GDPR. Overall, the skills I gained as a BOH Manager will enable me to excel in my new role as a Data Analyst.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Prime College
        caption: 2014 - 2018
        sub_title: BSc. Computer Science and Information Technology
        quote: >
          Relevant Courseworks
        description: | # this will include new lines to allow paragraphs
          Data Warehousing and Data Mining, Advanced Database Management System, Data Structures and Algorithms, Probability and Statistics, Statistics I/II, Numerical Methods, Linear Algebra, Discrete Structures, Technical Writing, OS, Software PM, Network and System Administration, Software Engineering, Cryptography, Network Security

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
